apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: batchtools
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: batchtools:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: tools_dockerfile
    git:
      ref: master
      uri: https://code.private.opequon.net/cfh/batch_job_templates.git
    type: Git
  strategy:
    dockerStrategy:
      env:
      - name: GIT_SSL_NO_VERIFY
        value: "true"
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
